name: Pull Request Action
on:
  workflow_dispatch:
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v3
      - name: set git config
        run: git config --local user.email "github-actions[bot]@users.noreply.github.com";
             git config --local user.name "github-actions[bot]";
      - name: run pre-commit
        run: set +e;  git branch pre-commit/${{ github.sha }}; git checkout pre-commit/${{ github.sha }}; pip install pre-commit && pre-commit run --all-files; git commit -a -m pre-commit; git push --all origin;
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create pull request
        run: gh pr create -H pre-commit/${{ github.sha }} -B main --title 'apply pre-commit' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
