name: Pull Request Action
on:
  workflow_dispatch:
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - uses: actions/setup-python@v3
      - name: run pre-commit
        run: pre-commit run --all-files; git commit -a -m pre-commit;
      - name: create pull request
        run: gh pr create -B pre-commit -H branch_to_merge --title 'apply pre-commit' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
